name: yaroo
description: Class and annotation based development with Pharaoh.
version: 0.0.1
repository: https://github.com/Pharaoh-Framework/pharaoh-turbo

environment:
  sdk: ^3.0.0

dependencies:
  spanner:
  pharaoh:
  meta: ^1.11.0
  collection: ^1.18.0
  dotenv: ^4.2.0
  get_it: ^7.6.4
  uuid: ^4.2.1
  analyzer:

dependency_overrides:
  spanner:
    git: 
      url: git@github.com:Pharaoh-Framework/pharaoh.git
      path: packages/spanner
  pharaoh:
    git: 
      url: git@github.com:Pharaoh-Framework/pharaoh.git
      path: packages/pharaoh

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
