name: pharaoh_turbo
description: Turbo-charged full-stack framework for Web & API development using Pharaoh.
version: 1.0.0
repository: https://github.com/Pharaoh-Framework/pharaoh-turbo

environment:
  sdk: ^3.0.0

dependencies:
  pharaoh:

dependency_overrides:
  spanner:
    git: 
      url: git@github.com:Pharaoh-Framework/pharaoh.git
      path: packages/spanner
  pharaoh:
    git: 
      url: git@github.com:Pharaoh-Framework/pharaoh.git
      path: packages/pharaoh
  
dev_dependencies:
  spookie: ^1.0.1
  lints: ^3.0.0

